# Generated by Django 4.1.7 on 2023-02-17 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stickynote',
            old_name='note',
            new_name='note_text',
        ),
    ]
