# Generated by Django 4.1.7 on 2023-02-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_stickynote_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickynote',
            name='background_color',
            field=models.CharField(max_length=255),
        ),
    ]
